version: 0.2

# See https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

env:
  shell: bash
  # secrets-manager:
  #   key: secret-id:json-key:version-stage:version-id

phases:
  install:
    # runtime-versions:
    #   # See https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html
    #   python: 3.13
    commands:
      - export release=AmazonLinux
      - dnf install -y dnf-plugins-core
      - dnf config-manager --add-repo https://rpm.releases.hashicorp.com/$release/hashicorp.repo
      - dnf install -y terraform

  pre_build:
    commands:
      - bash .github/tf.sh $WORKSPACE_PATH validate

  build:
    commands:
      - bash .github/tf.sh $WORKSPACE_PATH auto

  post_build:
    commands:
      - bash ./aws/org1/post_build.sh $WORKSPACE_PATH
