artifacts:
  files:
    - '**/*'
cache:
  # No effect for lambda: Cannot specify cache for lambda compute
  paths:
    # List of directories to cache, absolute or relative to the source directory
    - /tmp/.terraform.d-plugin-cache/**/*
# See https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
env:
  exported-variables:
    - TF_PLAN_EXIT_CODE # pass this variable up to CodePipeline so we can skip the Apply stage
  # secrets-manager:
  #   key: secret-id:json-key:version-stage:version-id

  parameter-store:
    TF_VAR_PLAN_SLACK_WEBHOOK_URL: TF_VAR_PLAN_SLACK_WEBHOOK_URL
    TF_VAR_aws_AISERVICES_OPT_OUT_POLICY: TF_VAR_aws_AISERVICES_OPT_OUT_POLICY
    TF_VAR_aws_CHATBOT_POLICY: TF_VAR_aws_CHATBOT_POLICY
    TF_VAR_aws_EC2_IMDSv2_POLICY: TF_VAR_aws_EC2_IMDSv2_POLICY
    TF_VAR_aws_EC2_NoIngressVPC_POLICY: TF_VAR_aws_EC2_NoIngressVPC_POLICY
    TF_VAR_aws_EC2_NoMarketplaceAMI_POLICY: TF_VAR_aws_EC2_NoMarketplaceAMI_POLICY
    TF_VAR_aws_EC2_NoPublicSharingAMI_POLICY: TF_VAR_aws_EC2_NoPublicSharingAMI_POLICY
    TF_VAR_aws_EC2_NoPublicSharingSnapshot_POLICY: TF_VAR_aws_EC2_NoPublicSharingSnapshot_POLICY
    TF_VAR_aws_EC2_NoSerial_POLICY: TF_VAR_aws_EC2_NoSerial_POLICY
    TF_VAR_aws_S3_POLICY: TF_VAR_aws_S3_POLICY
    TF_VAR_aws_SCP_OnlyOrgIdentityCenter_POLICY: TF_VAR_aws_SCP_OnlyOrgIdentityCenter_POLICY
    TF_VAR_aws_SCP_QuarantineDenyAll_POLICY: TF_VAR_aws_SCP_QuarantineDenyAll_POLICY
    TF_VAR_aws_TAG_iacdeployerEnumValues_POLICY: TF_VAR_aws_TAG_iacdeployerEnumValues_POLICY
    TF_VAR_aws_account_id_deployment_builds: TF_VAR_aws_account_id_deployment_builds
    TF_VAR_aws_account_id_management: TF_VAR_aws_account_id_management
    TF_VAR_aws_account_id_sandbox_bedrock: TF_VAR_aws_account_id_sandbox_bedrock
    TF_VAR_aws_account_id_security_aggregator: TF_VAR_aws_account_id_security_aggregator
    TF_VAR_aws_account_id_security_cloudtrail: TF_VAR_aws_account_id_security_cloudtrail
    TF_VAR_aws_controltower_landingzone_id: TF_VAR_aws_controltower_landingzone_id
    TF_VAR_aws_email_deployment_builds: TF_VAR_aws_email_deployment_builds
    TF_VAR_aws_email_sandbox_bedrock: TF_VAR_aws_email_sandbox_bedrock
    TF_VAR_aws_email_security_aggregator: TF_VAR_aws_email_security_aggregator
    TF_VAR_aws_email_security_cloudtrail: TF_VAR_aws_email_security_cloudtrail
    TF_VAR_aws_org_id: TF_VAR_aws_org_id
    TF_VAR_aws_org_root_id: TF_VAR_aws_org_root_id
    TF_VAR_aws_ou_id_deployment: TF_VAR_aws_ou_id_deployment
    TF_VAR_aws_ou_id_quarantine: TF_VAR_aws_ou_id_quarantine
    TF_VAR_aws_ou_id_sandbox: TF_VAR_aws_ou_id_sandbox
    TF_VAR_aws_ou_id_security: TF_VAR_aws_ou_id_security
    TF_VAR_codeconnection_deployment_builds: TF_VAR_codeconnection_deployment_builds
    TF_VAR_slack_team_name: TF_VAR_slack_team_name
  shell: bash
  variables:
    # See https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html
    CI: "true"
    TF_PLUGIN_CACHE_DIR: /tmp/.terraform.d-plugin-cache
    TF_TMP_LOG: /tmp/.terraform-plan.log
phases:
  build:
    commands:
      - |
        set -uo pipefail
        set +e
        bash .github/tf.sh $WORKSPACE_PATH plan 2>&1 |
          tee "$TF_TMP_LOG"
        export TF_PLAN_EXIT_CODE=$?
  install:
    # runtime-versions:
    #   # See https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html
    #   python: 3.13
    commands:
      - |
        mkdir -p "$TF_PLUGIN_CACHE_DIR"
        bash ./aws/org1/buildspec_install.sh
        export PATH=$PATH:~/bin
        terraform version
  post_build:
    commands:
      # 0 = Succeeded with empty diff (no changes), need to stop pipeline from going to TerraformApply
      # 2 = Succeeded with non-empty diff (changes present), need to continues pipeline to ApproveOrReject and TerraformApply
      # 1 = Error
      # don't exit on 2 because it will stop pipeline, so exit on 0 or 1
      - |
        if [[ $TF_PLAN_EXIT_CODE != 2 ]]; then
          exit $TF_PLAN_EXIT_CODE
        fi
    finally:
      - |
        bash ./aws/org1/buildspec_post_build.sh
  pre_build:
    commands:
      - bash ./aws/org1/buildspec_pre_build.sh
version: 0.2
